services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - AllowedOrigins=${ALLOWED_ORIGINS}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - JWT__SigningKey=${JWT_SIGNING_KEY}
    networks:
      - markettrust_network
    volumes:
      - dataprotection-keys:/home/appuser/.aspnet/DataProtection-Keys
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    networks:
      - markettrust_network
    volumes:
      - mssql-data:/var/opt/mssql

networks:
  markettrust_network:

volumes:
  mssql-data:
  dataprotection-keys: